// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TODO',
    appId: 'TODO',
    messagingSenderId: '1021931476908',
    projectId: 'trip-planner-TODO',
    authDomain: 'trip-planner-TODO.firebaseapp.com',
    storageBucket: 'trip-planner-TODO.firebasestorage.app',
    measurementId: 'G-SBQRL8HYL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrhH3FBqaGVC3ymhxRX_4_phmBAGJmkk0',
    appId: '1:1021931476908:android:0ef35750044f283fef4c09',
    messagingSenderId: '1021931476908',
    projectId: 'trip-planner-TODO',
    storageBucket: 'trip-planner-TODO.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9qNE74cvBUNkhVWSrGLvyEzZdrVeaj6A',
    appId: '1:1021931476908:ios:7fa06b741c70d6b3ef4c09',
    messagingSenderId: '1021931476908',
    projectId: 'trip-planner-TODO',
    storageBucket: 'trip-planner-TODO.firebasestorage.app',
    iosBundleId: 'com.gammagamma.trip-planner'
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9qNE74cvBUNkhVWSrGLvyEzZdrVeaj6A',
    appId: '1:1021931476908:ios:7fa06b741c70d6b3ef4c09',
    messagingSenderId: '1021931476908',
    projectId: 'trip-planner-TODO',
    storageBucket: 'trip-planner-TODO.firebasestorage.app',
    iosBundleId: 'com.gammagamma.trip-planner'
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI6-dz3FnJ_LwSnyD-6yAzYA9-kp2-cbM',
    appId: '1:1021931476908:web:a6612e8198ba1be7ef4c09',
    messagingSenderId: '1021931476908',
    projectId: 'trip-planner-TODO',
    authDomain: 'trip-planner-TODO.firebaseapp.com',
    storageBucket: 'trip-planner-TODO.firebasestorage.app',
    measurementId: 'G-SC9BLB1FCB',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBI6-dz3FnJ_LwSnyD-6yAzYA9-kp2-cbM',
    appId: '1:1021931476908:web:e5e20933f94c7474ef4c09',
    messagingSenderId: '1021931476908',
    projectId: 'trip-planner-TODO',
    authDomain: 'trip-planner-TODO.firebaseapp.com',
    storageBucket: 'trip-planner-TODO.firebasestorage.app',
    measurementId: 'G-SBQRL8HYL0',
  );

}
