// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDALB6ala7teypK6ZUFE7h7fEJO4E0AvNY',
    appId: '1:976595109556:web:7b895ffdf5ff903ec5b9e1',
    messagingSenderId: '976595109556',
    projectId: 'trip-planner-7fe7c',
    authDomain: 'trip-planner-7fe7c.firebaseapp.com',
    storageBucket: 'trip-planner-7fe7c.firebasestorage.app',
    measurementId: 'G-5JM4Q9QZHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy3UMPEiPc9d9YMAFZO0e8TqlqE0rl-YM',
    appId: '1:976595109556:android:348e91b693925592c5b9e1',
    messagingSenderId: '976595109556',
    projectId: 'trip-planner-7fe7c',
    storageBucket: 'trip-planner-7fe7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9NSZenRsEMjQ4YOsO4tcRooVh3Z7Q3ro',
    appId: '1:976595109556:ios:8be58a57d9fd0863c5b9e1',
    messagingSenderId: '976595109556',
    projectId: 'trip-planner-7fe7c',
    storageBucket: 'trip-planner-7fe7c.firebasestorage.app',
    iosClientId: '976595109556-r0tm2gg9f4intjoujevidsu4mpl0rd2i.apps.googleusercontent.com',
    iosBundleId: 'com.gammagamma.tripplanner.tripPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9NSZenRsEMjQ4YOsO4tcRooVh3Z7Q3ro',
    appId: '1:976595109556:ios:8be58a57d9fd0863c5b9e1',
    messagingSenderId: '976595109556',
    projectId: 'trip-planner-7fe7c',
    storageBucket: 'trip-planner-7fe7c.firebasestorage.app',
    iosClientId: '976595109556-r0tm2gg9f4intjoujevidsu4mpl0rd2i.apps.googleusercontent.com',
    iosBundleId: 'com.gammagamma.tripplanner.tripPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDALB6ala7teypK6ZUFE7h7fEJO4E0AvNY',
    appId: '1:976595109556:web:97c9a253414d22dfc5b9e1',
    messagingSenderId: '976595109556',
    projectId: 'trip-planner-7fe7c',
    authDomain: 'trip-planner-7fe7c.firebaseapp.com',
    storageBucket: 'trip-planner-7fe7c.firebasestorage.app',
    measurementId: 'G-F7HGGDRWMV',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDALB6ala7teypK6ZUFE7h7fEJO4E0AvNY',
    appId: '1:976595109556:web:7b895ffdf5ff903ec5b9e1',
    messagingSenderId: '976595109556',
    projectId: 'trip-planner-7fe7c',
    authDomain: 'trip-planner-7fe7c.firebaseapp.com',
    storageBucket: 'trip-planner-7fe7c.firebasestorage.app',
    measurementId: 'G-5JM4Q9QZHT',
  );

}